Upcoming events
NTNUI-Kite/website pull request #101
Opened 2018-05-19 12:54 UTC by emilps

closes #93

2018-05-19 18:37 UTC, oleob requested changes

2018-05-19 18:37 UTC, oleob commented on app/components/EventPreviews.jsx
> +function checkIfOpen(event) {
ES5 function? fyfy

2018-05-19 18:37 UTC, oleob commented on server/models/Event.js
> +    db.query('SELECT e.id, e.title, e.abstract, e.start, e.end, e.open, e.deadline, e.price, e.location, e.capacity, IFNULL(es.spots_taken,0) as spots_taken FROM events AS e LEFT JOIN (select event_i
Er det du som har endret dette? funker det?

2018-05-20 17:35 UTC, Henfau commented on server/models/Event.js
> +    db.query('SELECT e.id, e.title, e.abstract, e.start, e.end, e.open, e.deadline, e.price, e.location, e.capacity, IFNULL(es.spots_taken,0) as spots_taken FROM events AS e LEFT JOIN (select event_i
Det der er en hissig spørring

2018-06-02 12:09 UTC, merged